version: '3'
services:
  app:
    build:
      context: .
      target: development
    ports:
      - '3001:3001'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
